const menu = [
  {
    id: 1,
    title: "Crepe",
    category: "breakfast",
    price: 15.99,
    img: "/images/item-6.webp",
    desc: `Strawberries, blueberries, bananas, and Nutella wrapped in a crepe and topped with whipped cream and powdered sugar.`,
  },
  {
    id: 2,
    title: "Bionics",
    category: "lunch",
    price: 13.99,
    img: "/images/item-2.webp",
    desc: `Bionics is a delicious and healthy meal that is made with fresh vegetables and protein. It is a great option for those who are looking to eat healthy and stay fit.`,
  },
  {
    id: 3,
    title: "Mini Pancakes",
    category: "shakes",
    price: 6.99,
    img: "/images/item-3.webp",
    desc: `Mini Pancakes are a delicious and fun treat that is perfect for any occasion. They are made with fresh ingredients and are sure to be a hit with everyone who tries them.`,
  },
  {
    id: 4,
    title: "Churros",
    category: "breakfast",
    price: 20.99,
    img: "/images/item-4.webp",
    desc: `Churros are a delicious and sweet treat that is perfect for any occasion. They are made with fresh ingredients and are sure to be a hit with everyone who tries them.`,
  },
  {
    id: 5,
    title: "Banana Split",
    category: "lunch",
    price: 22.99,
    img: "/images/item-5.webp",
    desc: `Banana Split is a delicious and refreshing treat that is perfect for any occasion. It is made with fresh ingredients and is sure to be a hit with everyone who tries it.`,
  },
  {
    id: 6,
    title: "Nachos",
    category: "shakes",
    price: 18.99,
    img: "/images/item-6.webp",
    desc: `Nachos are a delicious and savory treat that is perfect for any occasion. They are made with fresh ingredients and are sure to be a hit with everyone who tries them.`,
  },
  {
    id: 7,
    title: "Tostilocos",
    category: "breakfast",
    price: 8.99,
    img: "/images/item-7.webp",
    desc: `Tostilocas are made with cucumber, jicama, peanuts, Japanese peanuts, and chamoy. They are a delicious and refreshing treat that is perfect for any occasion.`,
  },
  {
    id: 8,
    title: "Shave Ice",
    category: "lunch",
    price: 12.99,
    img: "/images/item-8.webp",
    desc: `Shave Ice of different flavors and colors like strawberry, mango, tamarind, and more. It is a delicious and refreshing treat that is perfect for any occasion.`,
  },
  {
    id: 9,
    title: "Milk Popsicle",
    category: "shakes",
    price: 16.99,
    img: "/images/item-9.webp",
    desc: `Milk popsicle of strawberry, chocolate, vanilla, and more. It is a delicious and refreshing treat that is perfect for any occasion.`,
  },
  {
    id: 10,
    title: "Water Popsicle",
    category: "summer",
    price: 16.99,
    img: "/images/item-10.webp",
    desc: `Water popsicle of strawberry, mango, tamarind, and more. It is a delicious and refreshing treat that is perfect for any occasion.`,
  },
  {
    id: 11,
    title: "Burger",
    category: "lunch",
    price: 11.99,
    img: "/images/item-11.webp",
    desc: `Classic beef burger with lettuce, tomato, onion, pickles, and special sauce. Served with fries.`,
  },
  {
    id: 12,
    title: "Pizza",
    category: "dinner",
    price: 14.99,
    img: "/images/item-12.webp",
    desc: `Delicious pizza with pepperoni, mushrooms, bell peppers, and mozzarella cheese.`,
  },
  {
    id: 13,
    title: "Salad",
    category: "lunch",
    price: 9.99,
    img: "/images/item-13.webp",
    desc: `Fresh garden salad with mixed greens, cherry tomatoes, cucumbers, carrots, and choice of dressing.`,
  },
  {
    id: 14,
    title: "Sushi",
    category: "dinner",
    price: 18.99,
    img: "/images/item-14.webp",
    desc: `Assorted sushi rolls with fresh salmon, tuna, avocado, and soy sauce.`,
  },
  {
    id: 15,
    title: "Ice Cream",
    category: "dessert",
    price: 5.99,
    img: "/images/item-15.webp",
    desc: `Creamy vanilla ice cream topped with chocolate syrup and sprinkles.`,
  },
  {
    id: 16,
    title: "Fried Chicken",
    category: "dinner",
    price: 16.99,
    img: "/images/item-16.webp",
    desc: `Crispy fried chicken served with mashed potatoes and gravy.`,
  },
  {
    id: 17,
    title: "Pasta",
    category: "dinner",
    price: 12.99,
    img: "/images/item-17.webp",
    desc: `Spaghetti with marinara sauce, meatballs, and parmesan cheese.`,
  },
  {
    id: 18,
    title: "Fish Tacos",
    category: "lunch",
    price: 15.99,
    img: "/images/item-18.webp",
    desc: `Grilled fish tacos with cabbage slaw, pico de gallo, and chipotle mayo.`,
  },
  {
    id: 19,
    title: "Smoothie",
    category: "shakes",
    price: 7.99,
    img: "/images/item-19.webp",
    desc: `Refreshing smoothie made with strawberries, bananas, and yogurt.`,
  },
  {
    id: 20,
    title: "Fruit Bowl",
    category: "breakfast",
    price: 10.99,
    img: "/images/item-20.webp",
    desc: `Fresh fruit bowl with a mix of seasonal fruits and honey drizzle.`,
  },
];

export default menu;
