const menu = [
  {
    id: 1,
    title: "Crepe",
    category: "sweet",
    price: 15.99,
    img: "/images/item-6.webp",
    desc: `Strawberries, blueberries, bananas, and Nutella wrapped in a crepe and topped with whipped cream and powdered sugar.`,
  },
  {
    id: 2,
    title: "Bionics",
    category: "fruit",
    price: 13.99,
    img: "/images/item-2.webp",
    desc: `Bionics is a delicious and healthy meal that is made with fresh vegetables and protein. It is a great option for those who are looking to eat healthy and stay fit.`,
  },
  {
    id: 3,
    title: "Mini Pancakes",
    category: "sweet",
    price: 6.99,
    img: "/images/item-3.webp",
    desc: `Mini Pancakes are a delicious and fun treat that is perfect for any occasion. They are made with fresh ingredients and are sure to be a hit with everyone who tries them.`,
  },
  {
    id: 4,
    title: "Churros",
    category: "sweet",
    price: 20.99,
    img: "/images/item-4.webp",
    desc: `Churros are a delicious and sweet treat that is perfect for any occasion. They are made with fresh ingredients and are sure to be a hit with everyone who tries them.`,
  },
  {
    id: 5,
    title: "Banana Split",
    category: "ice-cream",
    price: 22.99,
    img: "/images/item-5.webp",
    desc: `Banana Split is a delicious and refreshing treat that is perfect for any occasion. It is made with fresh ingredients and is sure to be a hit with everyone who tries it.`,
  },
  {
    id: 6,
    title: "Strawberry & Cream",
    category: "shakes",
    price: 18.99,
    img: "/images/item-6.webp",
    desc: `Strawberry & Cream is a delicious and refreshing treat that is perfect for any occasion. It is made with fresh strawberries and cream and is sure to be a hit with everyone who tries it.`,
  },
  {
    id: 7,
    title: "Churros With Ice Cream",
    category: "ice-cream",
    price: 8.99,
    img: "/images/item-7.webp",
    desc: `Tostilocas are made with cucumber, jicama, peanuts, Japanese peanuts, and chamoy. They are a delicious and refreshing treat that is perfect for any occasion.`,
  },
  {
    id: 8,
    title: "Frappe",
    category: "ice-cream",
    price: 12.99,
    img: "/images/item-8.webp",
    desc: `Frappe is a delicious and refreshing treat that is perfect for any occasion. It is made with fresh ingredients and is sure to be a hit with everyone who tries it.`,
  },
  {
    id: 9,
    title: "Elotes(Corn)",
    category: "Elotes",
    price: 16.99,
    img: "/images/item-9.webp",
    desc: `Elotes are made with corn, mayonnaise, butter, cheese, and chili powder. They are a delicious and refreshing treat that is perfect for any occasion.`,
  },
  {
    id: 10,
    title: "Cheeto Elotes(Corn)",
    category: "Elotes",
    price: 16.99,
    img: "/images/item-10.webp",
    desc: `Cheeto Elotes are made with corn, mayonnaise, butter, cheese, and Cheetos. They are a delicious and refreshing treat that is perfect for any occasion.`,
  },
  {
    id: 11,
    title: "Esquite(Corn in a cup)",
    category: "Elotes",
    price: 11.99,
    img: "/images/item-11.webp",
    desc: `Esquite is made with corn, mayonnaise, butter, cheese, and chili powder. It is a delicious and refreshing treat that is perfect for any occasion.`,
  },
  {
    id: 12,
    title: "Cheeto Esquite(Corn in a cup)",
    category: "Elotes",
    price: 14.99,
    img: "/images/item-12.webp",
    desc: `Cheeto Esquite is made with corn, mayonnaise, butter, cheese, and Cheetos. It is a delicious and refreshing treat that is perfect for any occasion.`,
  },
  {
    id: 13,
    title: "Nachos",
    category: "chips",
    price: 9.99,
    img: "/images/item-13.webp",
    desc: `Nachos are made with tortilla chips, cheese, jalapenos, and sour cream. They are a delicious and refreshing treat that is perfect for any occasion.`,
  },
  {
    id: 14,
    title: "TostiLocos",
    category: "chips",
    price: 18.99,
    img: "/images/item-14.webp",
    desc: `Tostilocas are made with cucumber, jicama, peanuts, Japanese peanuts, and chamoy. They are a delicious and refreshing treat that is perfect for any occasion.`,
  },
  {
    id: 15,
    title: "Tostiesquites/Doritos/Cheetos",
    category: "chips",
    price: 5.99,
    img: "/images/item-15.webp",
    desc: `Tostiesquites are made with corn, mayonnaise, butter, cheese, and chili powder. They are a delicious and refreshing treat that is perfect for any occasion.`,
  },
  {
    id: 16,
    title: "Prepared chicharron",
    category: "chips",
    price: 16.99,
    img: "/images/item-16.webp",
    desc: `Prepared chicharron is made with chicharron, cucumber, jicama, peanuts, Japanese peanuts, and chamoy. It is a delicious and refreshing treat that is perfect for any occasion.`,
  },
  {
    id: 17,
    title: "Ice Cream",
    category: "ice-cream",
    price: 12.99,
    img: "/images/item-17.webp",
    desc: `Ice cream is a delicious and refreshing treat that is perfect for any occasion. It is made with fresh ingredients and is sure to be a hit with everyone who tries it.`,
  },
  {
    id: 18,
    title: "Milk Popsicle",
    category: "ice-cream",
    price: 15.99,
    img: "/images/item-18.webp",
    desc: `Milk popsicle is a delicious and refreshing treat that is perfect for any occasion. It is made with fresh ingredients and is sure to be a hit with everyone who tries it.
    Flavor: Strawberry, Chocolate, Vanilla, Cookies & Cream, Mango, Pineapple, Coconut, Pistachio, Tamarind, Guava, Watermelon, Cantaloupe, Strawberry with cream, Chocolate with cream, Vanilla with cream, Cookies & Cream with cream, Mango with cream, Pineapple with cream, Coconut with cream, Pistachio with cream, Tamarind with cream, Guava with cream, Watermelon with cream, Cantaloupe with cream.`,
  },
  {
    id: 19,
    title: "Water Popsicle",
    category: "shakes",
    price: 7.99,
    img: "/images/item-19.webp",
    desc: `Water popsicle is a delicious and refreshing treat that is perfect for any occasion. It is made with fresh ingredients and is sure to be a hit with everyone who tries it. Flavor: Strawberry, Chocolate, Vanilla, Cookies & Cream, Mango, Pineapple, Coconut, Pistachio, Tamarind, Guava, Watermelon, Cantaloupe, Strawberry with cream, Chocolate with cream, Vanilla with cream, Cookies & Cream with cream, Mango with cream, Pineapple with cream, Coconut with cream, Pistachio with cream, Tamarind with cream, Guava with cream, Watermelon with cream, Cantaloupe with cream.`,
  },
  {
    id: 20,
    title: "Mangonada",
    category: "ice-cream",
    price: 10.99,
    img: "/images/item-20.webp",
    desc: `Mangonada is a delicious and refreshing treat that is perfect for any occasion. It is made with fresh ingredients and is sure to be a hit with everyone who tries it.`,
  },
  {
    id: 21,
    title: "Limonada Ice Cream",
    category: "ice-cream",
    price: 10.99,
    img: "/images/item-20.webp",
    desc: `Limonada Ice Cream is a delicious and refreshing treat that is perfect for any occasion. It is made with fresh ingredients and is sure to be a hit with everyone who tries it.`,
  },
  {
    id: 22,
    title: "Shaved Ice",
    category: "ice-cream",
    price: 10.99,
    img: "/images/item-20.webp",
    desc: `Shaved Ice is a delicious and refreshing treat that is perfect for any occasion. It is made with fresh ingredients and is sure to be a hit with everyone who tries it.`,
  },
  {
    id: 23,
    title: "Fruit Cocktail",
    category: "fruit",
    price: 10.99,
    img: "/images/item-20.webp",
    desc: `Fruit Cocktail is a delicious and refreshing treat that is perfect for any occasion. It is made with fresh ingredients and is sure to be a hit with everyone who tries it.`,
  },
  {
    id: 24,
    title: "Crazy Cucumber",
    category: "fruit",
    price: 10.99,
    img: "/images/item-20.webp",
    desc: `Crazy Cucumber is a delicious and refreshing treat that is perfect for any occasion. It is made with fresh ingredients and is sure to be a hit with everyone who tries it.`,
  },
  {
    id: 25,
    title: "Fresh Coconut",
    category: "fruit",
    price: 10.99,
    img: "/images/item-20.webp",
    desc: `Fresh Coconut is a delicious and refreshing treat that is perfect for any occasion. It is made with fresh ingredients and is sure to be a hit with everyone who tries it.`,
  },
  {
    id: 24,
    title: "Prepared Mango",
    category: "fruit",
    price: 10.99,
    img: "/images/item-20.webp",
    desc: `Prepared Mango is a delicious and refreshing treat that is perfect for any occasion. It is made with fresh ingredients and is sure to be a hit with everyone who tries it.`,
  },
  {
    id: 24,
    title: "Coconut Water",
    category: "fruit",
    price: 10.99,
    img: "/images/item-20.webp",
    desc: `Coconut Water is a delicious and refreshing treat that is perfect for any occasion. It is made with fresh ingredients and is sure to be a hit with everyone who tries it.`,
  },
  {
    id: 24,
    title: "Water of the day",
    category: "fruit",
    price: 10.99,
    img: "/images/item-20.webp",
    desc: ` Water of the day is a delicious and refreshing treat that is perfect for any occasion. It is made with fresh ingredients and is sure to be a hit with everyone who tries it.`,
  },
];

export default menu;
